### ISSUE TITLE
is this cserver support add plugin write in LUA language

### ISSUE THREAD

**Issue by codingwatching** [igor725/cserver#3]
Hi @igor725 
I found this project and it is an awesome server for Minecraft classic
In the future can I write Plugin for this server using the LUA language? I love LUA like in your LuaClassic server
Thank you so much!

**Comment by igor725** [comment]
Yes, this server supports Lua scripts. But you need to install cs-lua plugin to activate Lua scripting feature. You can find it in my profile.

**Comment by codingwatching** [comment]
Thank you so much! It would be great if you provide an example for it!

**Comment by igor725** [comment]
> Thank you so much! It would be great if you provide an example for it!

This plugin is not ready yet, so the set of Lua API methods and objects changes almost every day.

**Comment by wildrun0** [comment]
> example for it!

I just wrote a simple plugin so [take a look at it](https://github.com/wildrun0/etools)

**Comment by codingwatching** [comment]
@wildrun0 Thank you!
