### ISSUE TITLE
Can I have a compiled version please?

### ISSUE THREAD

**Issue by Minecraft-Classic-Server-Archive** [igor725/cserver#4]
Can't wrap my head around the build.bat thing

**Comment by igor725** [comment]
[Compiled](https://github.com/igor725/cserver/suites/6717529138/artifacts/255826171) binaries of the server for each commit are in the "Actions" tab
![изображение](https://user-images.githubusercontent.com/40758030/171046264-96c8240d-f224-458c-819a-fc9d846b63de.png)
